BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "embedaddy-bsp-common"
BBFILE_PATTERN_embedaddy-bsp-common := "^${LAYERDIR}/"
BBFILE_PRIORITY_embedaddy-bsp-common = "8"

LAYERDEPENDS_embedaddy-bsp-common = "core"
LAYERSERIES_COMPAT_embedaddy-bsp-common = "scarthgap"
LAYERVERSION_embedaddy-bsp-common = "1"
