# LAYERDIR on BBPATH puts wic/ on WKS_SEARCH_PATH.
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "embedaddy-distro"
BBFILE_PATTERN_embedaddy-distro := "^${LAYERDIR}/"

# Above meta-st-stm32mp-addons (7).
BBFILE_PRIORITY_embedaddy-distro = "8"

LAYERDEPENDS_embedaddy-distro = "core"
LAYERSERIES_COMPAT_embedaddy-distro = "scarthgap"
LAYERVERSION_embedaddy-distro = "1"
