# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-embedaddy-bsp-sophgo"
BBFILE_PATTERN_meta-embedaddy-bsp-sophgo = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-embedaddy-bsp-sophgo = "6"

LAYERDEPENDS_meta-embedaddy-bsp-sophgo = "core"
LAYERSERIES_COMPAT_meta-embedaddy-bsp-sophgo = "scarthgap"
