DISTRO = "embdy-sd"
DISTROOVERRIDES .= ":embdy-distro"
DISTRO_NAME = "Embedaddy Development Distro (systemd)"
DISTRO_VERSION = "1.0"
MAINTAINER = "jpaulo.silvagoncalves@gmail.com"
SDK_VENDOR = "-embdysdsdk"

EMBEDADDY_DISTRO_FEATURES = "acl xattr ipv4 ipv6 vfat seccomp pni-names usrmerge"
DISTRO_FEATURES = "${EMBEDADDY_DISTRO_FEATURES}"

INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_base-utils = "busybox"
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_base-utils-hwclock = ""

PACKAGE_CLASSES = "package_ipk"

IMAGE_LINGUAS ?= "en-us"

INHERIT += "buildhistory"
BUILDHISTORY_COMMIT = "1"
BUILDHISTORY_FEATURES ?= "image"
