#@TYPE: Machine
#@NAME: milkv-duos
#@SOC: SOPHGO SG2000
#@DESCRIPTION: Machine configuration for Milk-V Duo S

# Settings shared by all Milk-V Duo boards (duo, duo256m, duos)

require conf/machine/include/riscv/tune-riscv.inc

MACHINEOVERRIDES .= ":milkv-duo-common"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-embdy-mainline"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-embdy-mainline"

PREFERRED_VERSION_openocd-native = "riscv"
PREFERRED_VERSION_openocd = "riscv"


# Machine Configuration
SERIAL_CONSOLES = "115200;ttyS0"
MACHINE_FEATURES = "screen keyboard ext2 serial"

# OpenSBI
RISCV_SBI_PLAT = "generic"

# U-Boot Extlinux
UBOOT_EXTLINUX = "1"
UBOOT_EXTLINUX_LABELS = "embdy"
UBOOT_EXTLINUX_MENU_DESCRIPTION:embdy = "Linux MilkV DuoS"
UBOOT_EXTLINUX_KERNEL_IMAGE = "../${KERNEL_IMAGETYPE}"
UBOOT_EXTLINUX_FDT ?= "../${@os.path.basename(d.getVar('KERNEL_DEVICETREE'))}"
UBOOT_EXTLINUX_FDTDIR = ""
UBOOT_EXTLINUX_ROOT = "root=PARTUUID=257bf3ad-3d89-4b5c-844d-3bbeff52d92f"
UBOOT_EXTLINUX_CONSOLE = "console=ttyS0,115200"
UBOOT_EXTLINUX_KERNEL_ARGS = "rootwait rw earlycon=sbi"

# U-Boot Config
UBOOT_MACHINE ?= "milkv_duos_defconfig"

# Kernel Configuration
KERNEL_CLASSES = "kernel"
KERNEL_IMAGETYPE = "Image.gz"
KERNEL_DEVICETREE ?= "sophgo/sg2000-milkv-duo-s.dtb"

# Image Configuration
#WIC_CREATE_EXTRA_ARGS ?= "--no-fstab-update"
IMAGE_FSTYPES += "wic.gz wic.bmap ext4 tar.gz"
EXTRA_IMAGEDEPENDS += "milkv-duo-fsbl"
WKS_FILE ?= "embdy-milkv-duos-sd.wks"
WKS_FILE_DEPENDS:append = " milkv-duo-fsbl virtual/bootloader"
IMAGE_BOOT_FILES ?= " \
                    sg2000-milkv-duo-s.dtb \
                    fip.bin \
                    {KERNEL_IMAGETYPE} \
"
